spring.datasource.url=jdbc:mysql://mysql-1e8c3b91-malitzinjrm16-7607.e.aivencloud.com:24325/defaultdb?useSSL=true&requireSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_h7l9iGsfIppZ62PTQ-t
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true